src/background/blockInterval.ts
src/background/contracts.ts
src/background/index.ts
src/background/interface.ts
src/background/url.ts
src/background/urlList.ts
src/components/utils/sendMessageBackground.tsx

Improve code by using `Type` instead of `any`
- Change 1.
- ...
- Change 1.
- ...

refacto: Replace message: any in backgroud by a type

---

src/components/block/blockDetails.tsx
src/components/block/displayBlockInfo.tsx
src/components/contractInteraction/messageActions.ts
src/components/hooks/hooks.tsx
src/components/predeployedAccounts/predeployedAccounts.tsx
src/components/predeployedAccounts/predeployedAccountsInline.tsx
src/components/utils/utils.tsx
src/popup/Popup.tsx

Transactions History for the current block.
Remove `amount` cause we don't have any.
- Change 1.
- ...
- Change 1.
- ...

feat: transaction list for the current block

---

src/components/block/blockDetails.tsx
src/components/home/home.tsx

Adding ability to navigate to specific home page tabs programatically so proper navigation can be implemented.

:sparkles: Home page tab navigation

---

src/background/constants.ts
src/background/contracts.ts
src/components/account/selectedAccount.tsx
src/components/settings/modifyBalance.tsx
src/popup/Popup.tsx

Users can define a new balance for redeployed accounts.
New balance needs to be in `WEI`
This is for Issue [72](https://github.com/0xSpaceShard/starknet-rivet/issues/72)
- Change 1.

feat: set a new balance for account

---

src/background/contracts.ts
src/background/index.ts
src/background/utils.ts
src/components/block/BlockList.tsx
src/components/confirmationSection/confirmationSection.tsx
src/components/contractInteraction/messageActions.ts
src/components/contractInteraction/requestMessagesHandler/addDeclareTransactionHandler.ts
src/components/contractInteraction/requestMessagesHandler/deploymentDataHandler.ts
src/components/contractInteraction/requestMessagesHandler/invokeTransaction.ts
src/components/contractInteraction/requestMessagesHandler/requestChainIdHandler.ts
src/components/contractInteraction/requestMessagesHandler/requestMessageHandler.ts
src/components/contractInteraction/requestMessagesHandler/switchStarknetChainHandler.ts
src/components/contractInteraction/requestMessagesHandler/watchAsset.ts
src/components/handleWalletMessages/declareContractMessage.tsx
src/components/handleWalletMessages/switchStarknetChainMessage.tsx
src/components/handleWalletMessages/watchAssetMessage.tsx
src/contentScript/index.ts
src/popup/Popup.tsx

Message Handler function Not Implemented:
- wallet_addStarknetChain 
-  starknet_supportedSpecs
- wallet_deploymentData -> Would be done once `add new Account feature` is implemented.
Message Handler function Implemented:
- wallet_switchStarknetChain
- wallet_watchAsset 
- wallet_requestAccounts
- wallet_getPermissions  -> (Return always true)
- wallet_requestChainId
- starknet_addInvokeTransaction: addInvokeTransactionHandler,
- starknet_signTypedData: signTypedDataHandler,
Need More test
- wallet_addDeclareTransaction: addDeclareTransactionHandler
- Change 1.
- ...

feat: message handler function

---

.eslintrc
jest.config.js
package-lock.json
package.json
src/components/contractInteraction/requestMessagesHandler/addDeclareTransactionHandler.test.ts
src/components/contractInteraction/requestMessagesHandler/addDeclareTransactionHandler.ts
src/components/contractInteraction/requestMessagesHandler/invokeTransaction.test.ts
src/components/contractInteraction/requestMessagesHandler/requestAccounts.test.ts
src/components/contractInteraction/requestMessagesHandler/requestChainIdHandler.test.ts
src/components/contractInteraction/requestMessagesHandler/signTypedData.test.ts
src/components/contractInteraction/requestMessagesHandler/switchStarknetChainHandler.test.ts
src/components/contractInteraction/requestMessagesHandler/watchAsset.test.ts
src/components/utils/utils.test.ts
src/components/utils/utils.tsx

#25 
Tests added and can be run via npm run test

:white_check_mark: Added Jest and tests

---

README.md
package-lock.json
package.json
starknet-run/starknet-run.sh

Closes #80 
I've changed the bash script so that l1 node param is false by default

updated bash script and readme

---

src/components/registerRunningDocker/registerRunningDocker.tsx

fix: routing to accounts from docker config

---

README.md

Update README with instructions how to connect to an existing dapp

---

src/background/interface.ts
src/background/syncStorage.ts
src/background/utils.ts
src/components/account/selectedAccount.tsx
src/components/block/displayBlockInfo.tsx
src/components/home/home.tsx
src/components/predeployedAccounts/predeployedAccounts.tsx
src/components/settings/appSettings.tsx
src/components/utils/spinner.css
src/components/utils/spinner.tsx
src/components/utils/utils.test.ts
src/components/utils/utils.tsx
src/popup/Popup.css
src/popup/Popup.tsx
src/popup/index.css

Resolves #73 #92 
Users can create new accounts

🎉 Account Creation

---

src/components/predeployedAccounts/AccountItem.tsx
src/components/predeployedAccounts/predeployedAccounts.tsx

AccountInfo param fix
Styling updates
Added AccountInfo for custom accounts

:bug: :lipstick: Account copy address updates

---

src/components/settings/blockConfiguration.tsx
src/components/status/statusHeader.tsx
src/popup/Popup.tsx

Closes #102 
- Change 1.
- ...
- Change 1.
- ...

:sparkles: Added mining mode in status header

---

src/components/account/selectedAccount.tsx
src/components/settings/modifyBalance.tsx

Resolves #103 
Modify balance input now takes ETH instead of WEI

:sparkles: :lipstick: Modify Balance Updates

---

src/background/constants.ts
src/components/registerRunningDocker/registerRunningDocker.tsx

Resolves #101 
Register Docker Command page now has a button to add the local devnet to the url list.

:sparkles: Add local devnet action

---

src/background/utils.ts
src/components/block/BlockList.tsx
src/components/block/blockDetails.tsx
src/components/home/home.tsx
src/components/hooks/hooks.tsx
src/components/settings/blockConfiguration.tsx
src/components/settings/modifyBalance.tsx
src/components/transaction/TransactionDetails.tsx
src/components/transaction/TransactionList.tsx
src/popup/Popup.tsx

Resolves #88
Resolves #104
Resolves #109
Resolves #111

✨ 🐛 💄 Blocks & Transaction updates | Transaction details

---

src/components/account/selectedAccount.tsx
src/components/block/BlockList.tsx
src/components/context/context.tsx
src/components/context/interfaces.ts
src/components/settings/modifyBalance.tsx
src/popup/Popup.tsx

Resolves #68 
Resolves #115 
Account details page shows the latest transactions

:sparkles: :bug: Account transaction history

---

src/components/account/selectedAccount.tsx
src/components/hooks/hooks.tsx
src/components/transaction/TransactionDetails.tsx
src/components/transaction/TransactionList.tsx

:sparkles: Transactions feature improvements

---

.eslintrc
src/background/utils.ts
src/components/account/selectedAccount.tsx
src/components/hooks/hooks.tsx
src/components/settings/appSettings.tsx
src/components/settings/gasPriceModification.tsx
src/components/transaction/TransactionList.tsx
src/popup/Popup.tsx

Resolves #116 
Resolves #117 
* Added load more button for account transactions and transactions list tab
* Added gas price modification page in the settings

:sparkles: Transaction Updates | Gas Price Modification

---

src/background/contracts.ts
src/components/account/accountSend.tsx
src/components/account/selectedAccount.tsx
src/popup/Popup.tsx

Resolves #84 
Users can now send ETH to any recipient from an account.

:sparkles: Send ETH from one account to another

---

src/background/contracts.ts
src/background/interface.ts
src/background/syncStorage.ts
src/components/context/context.tsx
src/components/context/interfaces.ts
src/components/contract/ContractItem.tsx
src/components/contract/ContractList.tsx
src/components/hooks/useDeployedContracts.ts
src/components/settings/declareSmartContract.tsx
src/components/settings/deploySmartContract.tsx

Resolves #123 & #124 
Now showing names, addresses & class hashes of deployed contracts on the contracts tab.
Declare & deploy workflow is also improved.

✨ Deployed contract info

---

src/components/account/selectedAccount.tsx
src/components/account/tokenDropdown.tsx
src/components/block/displayBlockInfo.tsx
src/components/hooks/useTokens.ts
src/components/transaction/TransactionDetails.tsx

Resolves #130
- More details when clicking on a transaction

✨ More transaction details & Refactored code

---

.eslintrc
src/background/alarms.ts
src/background/constants.ts
src/background/contracts.ts
src/background/index.ts
src/background/syncStorage.ts
src/background/utils.ts
src/components/account/selectedAccount.tsx
src/components/block/blockDetails.tsx
src/components/checkDevnetStatus/checkDevnetStatus.tsx
src/components/handleWalletMessages/switchStarknetChainMessage.tsx
src/components/hooks/useTokens.ts
src/components/predeployedAccounts/predeployedAccounts.tsx
src/components/registerRunningDocker/registerRunningDocker.tsx
src/components/settings/declareSmartContract.tsx
src/components/settings/deploySmartContract.tsx
src/components/settings/modifyBalance.tsx
src/components/utils/sendMessageBackground.tsx
src/contentScript/index.ts
src/contentScript/inpage.ts
src/popup/Popup.tsx

💄♻️ Removed console errors / Selected account UI updates

---

package-lock.json
package.json
src/background/alarms.ts
src/background/analytics.ts
src/background/contracts.ts
src/background/index.ts
src/background/syncStorage.ts
src/background/utils.ts
src/components/account/selectedAccount.tsx
src/components/block/blockDetails.tsx
src/components/checkDevnetStatus/checkDevnetStatus.tsx
src/components/handleWalletMessages/switchStarknetChainMessage.tsx
src/components/predeployedAccounts/predeployedAccounts.tsx
src/components/registerRunningDocker/registerRunningDocker.tsx
src/components/settings/declareSmartContract.tsx
src/components/settings/deploySmartContract.tsx
src/components/settings/modifyBalance.tsx
src/components/utils/sendMessageBackground.tsx
src/contentScript/index.ts
src/contentScript/inpage.ts
src/manifest.ts
src/popup/Popup.tsx

✨ Added google analytics error logging

---

package-lock.json
src/manifest.ts

🔧🔥 Removed host permissions from manifest

---

package-lock.json
package.json
src/components/account/selectedAccount.tsx
src/components/predeployedAccounts/predeployedAccounts.tsx

Data fetch logic moved to selected account page to enable direct navigation

🐛💄♻️ Updated account data fetch logic

---

.github/workflows/automated-release.yml

* Removed unused extension pages
* Added release workflow

:construction_worker: Added release workflow user config

---

.github/workflows/automated-release.yml

* Removed unused extension pages
* Added release workflow

👷 Updated release workflow with develop-spaceshard user config and access token

---

.github/workflows/automated-release.yml

* Removed unused extension pages
* Added release workflow

:construction_worker: :bug: Fixed release workflow repo url

---

src/manifest.ts

:wrench::lock: Removed activeTab and tabs permissions from manifest
